name: Django Regression Tests

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # Use the version your project requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Or `pipenv install` if you're using Pipenv

    - name: Set up the database (SQLite)
      run: |
        # Run migrations for SQLite (default Django database)
        python manage.py migrate  # Apply migrations to the database

    - name: Run tests with pytest and coverage
      run: |
        pytest --maxfail=1 --disable-warnings -q --cov=myapp --cov-report=html:htmlcov  # Ensure to replace 'myapp' with your app name

    - name: Upload test results (Optional)
      if: success()  # Upload test results only if tests pass
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: /path/to/test/results  # Optional: Path to store your test results if you are generating a results file (like JUnit)

    - name: Upload coverage report
      if: success()  # Upload coverage report only if tests pass
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report  # The name of the uploaded artifact
        path: htmlcov/  # The path to the directory containing the coverage report
